# Eat Safe, Love

## Notebook Set Up

In [1]:
# Import dependencies
from pymongo import MongoClient
from pprint import pprint
import pandas as pd

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
uk_foods = mongo.uk_food

In [4]:
# review the collections in our database
print(uk_foods.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = uk_foods.establishments

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [6]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}
hygiene_twenty = establishments.find(query)

# Use count_documents to display the number of documents in the result
print(f"""{establishments.count_documents(query)} establishments have a hygiene score equal to 20.
  """)

# Display the first document in the results using pprint
pprint(establishments.find_one(query))

41 establishments have a hygiene score equal to 20.

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': '0',
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6406726bc8c84a6faa3ce64d'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [7]:
# Convert the result to a Pandas DataFrame
## convert cursor object into a list of dictionaries using list comprehension.
data = [doc for doc in hygiene_twenty]
## Place in DF
df = pd.DataFrame(data)

# Display the number of rows in the DataFrame
print(f"There are {len(df)} rows in the DataFrame.")
# Display the first 10 rows of the DataFrame
df.head(10)

There are 41 rows in the DataFrame.

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,6406726bc8c84a6faa3ce64d,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,6406726bc8c84a6faa3ce9ce,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
2,6406726bc8c84a6faa3cecd7,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 1.15927, 'latitude': 51.789429}",,4619.656144,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
3,6406726bc8c84a6faa3ceec6,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.10202, 'latitude': 50.770885}",,4620.421725,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
4,6406726bc8c84a6faa3ceed5,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,http://www.lewes-eastbourne.gov.uk/,ehealth.ldc@lewes-eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 10, 'ConfidenceI...",FHRS,"{'longitude': 0.101446, 'latitude': 50.770724}",,4620.437179,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
5,6406726bc8c84a6faa3cf874,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.736349, 'latitude': 51.541448}",,4625.565258,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
6,6406726bc8c84a6faa3cfa95,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,http://www.southend.gov.uk,EnvironmentalHealth@southend.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.7121671, 'latitude': 51.5350065}",,4626.200132,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
7,6406726bc8c84a6faa3d0fc0,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,http://www.rochford.gov.uk,customerservices@rochford.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 0.602364, 'latitude': 51.591515}",,4632.276890,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
8,6406726bc8c84a6faa3d1406,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,http://www.sevenoaks.gov.uk/,environmental.health@sevenoaks.gov.uk,"{'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...",FHRS,"{'longitude': 0.146449998021126, 'latitude': 5...",,4633.934041,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."
9,6406726bc8c84a6faa3d1c16,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,http://www.basildon.gov.uk,ehs@basildon.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.462307, 'latitude': 51.57005}",,4636.552523,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'http://api.ratings.f..."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [25]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
## As ratings are stored as strings to account for a 'pass' rating, I used
## "$in" as opposed to "$gte" to search for all values at or above 4.
## All values at or above 4 in this range are "4" and "5". 
query = {
    "LocalAuthorityName": {'$regex':"London"},
    "RatingValue": {'$in': ["4","5"]}
}

## Choose most relevant fields for easier viewing
fields = {'LocalAuthorityBusinessID':1,
          'BusinessName':1,
          'BusinessType':1,
          'RatingValue': 1, 
          'LocalAuthorityName': 1,   
}

## Store query
london_result = establishments.find(query, fields)

# Use count_documents to display the number of documents in the result
count = establishments.count_documents(query)
print(f"There are {count} documents in the result.")

# Display the first document in the results using pprint
pprint(establishments.find_one(query, fields))

There are 33 documents in the result.
{'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityName': 'City of London Corporation',
 'RatingValue': '4',
 '_id': ObjectId('6406726bc8c84a6faa3d0068')}

In [26]:
# Convert the result to a Pandas DataFrame
london_data = [doc for doc in london_result]
london_df = pd.DataFrame(london_data)

# Display the number of rows in the DataFrame
print(f"There are {count} establishments in London that have a rating of 4 or greater.")

# Display the first 10 rows of the DataFrame
london_df.head(10)

There are 33 establishments in London that have a rating of 4 or greater.

,_id,LocalAuthorityBusinessID,BusinessName,BusinessType,RatingValue,LocalAuthorityName
0,6406726bc8c84a6faa3d0068,PI/000025307,Charlie's,Other catering premises,4,City of London Corporation
1,6406726bc8c84a6faa3d038e,PI/000034075,Mv City Cruises Erasmus,Other catering premises,5,City of London Corporation
2,6406726bc8c84a6faa3d0ed9,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,4,City of London Corporation
3,6406726bc8c84a6faa3d1cda,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,5,City of London Corporation
4,6406726bc8c84a6faa3d1cdc,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,5,City of London Corporation
5,6406726bc8c84a6faa3d23e5,PI/000019066,Mv Valulla,Other catering premises,5,City of London Corporation
6,6406726cc8c84a6faa3d44f2,PI/000002538,Tereza Joanne,Other catering premises,5,City of London Corporation
7,6406726cc8c84a6faa3d48b8,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,4,City of London Corporation
8,6406726cc8c84a6faa3d48d3,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,5,City of London Corporation
9,6406726cc8c84a6faa3d48d4,PI/000016185,WH Smith,Retailers - other,5,City of London Corporation

### 3. What are the top 5 establishments with a `RatingValue` rating value of '5', sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [29]:
## Look up Penang Flavour's lat/long
Penang = establishments.find_one(
    {"BusinessName":{"$regex":"Penang"}}, 
    {"BusinessName":1,
     "geocode.latitude":1,
     "geocode.longitude":1, 
     'LocalAuthorityName': 1})
Penang

{'_id': ObjectId('6406727352141c303915fe05'),
 'BusinessName': 'Penang Flavours',
 'LocalAuthorityName': 'Greenwich',
 'geocode': {'longitude': 0.08384, 'latitude': 51.490142}}

In [11]:
## Test 'get()' method to access dictionary values (to store lat/long as variable)
Penang.get('geocode').get('longitude')

0.08384

In [16]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
latitude = Penang.get('geocode').get('latitude') #51.490142
longitude = Penang.get('geocode').get('longitude') #0.08384

## Match Query
query = {'RatingValue':'5', #RatingValue equals 5
                   'geocode.latitude': #Lat within .01 degrees
                         {'$gte': (latitude - degree_search), 
                          '$lt': (latitude + degree_search)
                         },
                    'geocode.longitude': #Long within .01 degrees
                         {'$gte': (longitude - degree_search), 
                          '$lt': (longitude + degree_search)
                         },
                    'scores.Hygiene': #Exclude results w/ no hygiene score. 
                         {'$ne': None}
        }

## Choose fields (for easier viewing)
fields = {'LocalAuthorityBusinessID':1,
          'BusinessName':1,
          'BusinessType':1,
          'RatingValue': 1, 
          'geocode.latitude': 1,
          'geocode.longitude': 1,
          'scores.Hygiene': 1,
          'LocalAuthorityName': 1   
}

## Sort query in ascending order
sort =  [('scores.Hygiene', 1)]

## Limit results to five
limit = 5

## Combine queries
results = list(establishments.find(query, fields).sort(sort).limit(limit))

# Print the results
pprint(results)

[{'BusinessName': 'Volunteer',
  'BusinessType': 'Pub/bar/nightclub',
  'LocalAuthorityBusinessID': 'PI/000116619',
  'LocalAuthorityName': 'Greenwich',
  'RatingValue': '5',
  '_id': ObjectId('6406726cc8c84a6faa3d3eac'),
  'geocode': {'latitude': 51.4873437, 'longitude': 0.09208},
  'scores': {'Hygiene': 0}},
 {'BusinessName': 'Plumstead Manor Nursery',
  'BusinessType': 'Caring Premises',
  'LocalAuthorityBusinessID': 'PI/000179088',
  'LocalAuthorityName': 'Greenwich',
  'RatingValue': '5',
  '_id': ObjectId('6406726cc8c84a6faa3d3ec5'),
  'geocode': {'latitude': 51.481517791748, 'longitude': 0.0859939977526665},
  'scores': {'Hygiene': 0}},
 {'BusinessName': 'Atlantic Fish Bar',
  'BusinessType': 'Takeaway/sandwich shop',
  'LocalAuthorityBusinessID': 'PI/000086506',
  'LocalAuthorityName': 'Greenwich',
  'RatingValue': '5',
  '_id': ObjectId('6406726cc8c84a6faa3d3ec6'),
  'geocode': {'latitude': 51.4867296, 'longitude': 0.0912164},
  'scores': {'Hygiene': 0}},
 {'BusinessName': 'Iceland',
  'BusinessType': 'Retailers - supermarkets/hypermarkets',
  'LocalAuthorityBusinessID': 'PI/000178842',
  'LocalAuthorityName': 'Greenwich',
  'RatingValue': '5',
  '_id': ObjectId('6406726cc8c84a6faa3d3e7f'),
  'geocode': {'latitude': 51.4871482849121, 'longitude': 0.0924199968576431},
  'scores': {'Hygiene': 0}},
 {'BusinessName': 'Howe and Co Fish and Chips - Van 17',
  'BusinessType': 'Mobile caterer',
  'LocalAuthorityBusinessID': '14425',
  'LocalAuthorityName': 'Greenwich',
  'RatingValue': '5',
  '_id': ObjectId('6406726cc8c84a6faa3d3e8e'),
  'geocode': {'latitude': 51.4875335693359, 'longitude': 0.0925370007753372},
  'scores': {'Hygiene': 0}}]

In [27]:
# Convert result to Pandas DataFrame
## Apply json_normalize to view nested dictionaries as seperate columns. 
normalized_results = pd.json_normalize(results)
near_Penang = pd.DataFrame(normalized_results)
near_Penang.head()

,_id,LocalAuthorityBusinessID,BusinessName,BusinessType,RatingValue,LocalAuthorityName,scores.Hygiene,geocode.longitude,geocode.latitude
0,6406726cc8c84a6faa3d3eac,PI/000116619,Volunteer,Pub/bar/nightclub,5,Greenwich,0,0.092080,51.487344
1,6406726cc8c84a6faa3d3ec5,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Greenwich,0,0.085994,51.481518
2,6406726cc8c84a6faa3d3ec6,PI/000086506,Atlantic Fish Bar,Takeaway/sandwich shop,5,Greenwich,0,0.091216,51.486730
3,6406726cc8c84a6faa3d3e7f,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,5,Greenwich,0,0.092420,51.487148
4,6406726cc8c84a6faa3d3e8e,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,5,Greenwich,0,0.092537,51.487534

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [30]:
# Create a pipeline that: 
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

## Match Query, with hygiene as zero. 
match_query = {'$match': {'scores.Hygiene': 0}}

## Group Query, by local authority
group_query = {
    '$group': {
        '_id': "$LocalAuthorityName",
        'count_per_local': {'$sum':1}
    }
}

## Sort Query, highest to lowest
sort_query = {
    '$sort': {
        'count_per_local': -1
    }
}

## put pipeline together
pipeline = [match_query, group_query, sort_query]
results = list(establishments.aggregate(pipeline))

# Print the number of documents in the result
print(f"There are {len(results)} local authorities that have establishments with hygiene scores of zero.")

# Print the first 10 results
pprint(results[0:10])

There are 55 local authorities that have establishments with hygiene scores of zero.
[{'_id': 'Thanet', 'count_per_local': 1130},
 {'_id': 'Greenwich', 'count_per_local': 882},
 {'_id': 'Maidstone', 'count_per_local': 713},
 {'_id': 'Newham', 'count_per_local': 711},
 {'_id': 'Swale', 'count_per_local': 686},
 {'_id': 'Chelmsford', 'count_per_local': 680},
 {'_id': 'Medway', 'count_per_local': 672},
 {'_id': 'Bexley', 'count_per_local': 607},
 {'_id': 'Southend-On-Sea', 'count_per_local': 586},
 {'_id': 'Tendring', 'count_per_local': 542}]

In [34]:
# Convert the result to a Pandas DataFrame
hygienic_authorities = pd.DataFrame(results)

# Display the number of rows in the DataFrame
print(f"There are {len(hygienic_authorities)} rows in this DataFrame.")

# Display the first 10 rows of the DataFrame
hygienic_authorities.head(10)

There are 55 rows in this DataFrame.

               _id  count_per_local
0           Thanet             1130
1        Greenwich              882
2        Maidstone              713
3           Newham              711
4            Swale              686
5       Chelmsford              680
6           Medway              672
7           Bexley              607
8  Southend-On-Sea              586
9         Tendring              542